web:
  image: nginx:1.12
  ports:
    - "8081:80"
  volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  dockerfile: Dockerfile
  volumes:
    - ./code:/code
  links:
    - maria

maria:
  image: mariadb
  volumes:
    - ./install/create.sql:/docker-entrypoint-initdb.d/create.sql
  environment:
    MYSQL_ROOT_PASSWORD: azerty
  ports:
    - 3306:3306
